# Generated by Django 2.0.2 on 2018-02-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180215_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
